import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  earthquakesList: [
    {
      type: 'FeatureCollection',
      metadata: {
        generated: 1669279489000,
        url: 'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=2022-11-21&endtime=2022-11-22&minmagnitude=5',
        title: 'USGS Earthquakes',
        status: 200,
        api: '1.13.6',
        count: 6,
      },
      features: [
        {
          type: 'Feature',
          properties: {
            mag: 5.1,
            place: null,
            time: 1669069545614,
            updated: 1669072745040,
            tz: null,
            url: 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000iren',
            detail: 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000iren&format=geojson',
            felt: null,
            cdi: null,
            mmi: null,
            alert: null,
            status: 'reviewed',
            tsunami: 0,
            sig: 400,
            net: 'us',
            code: '7000iren',
            ids: ',us7000iren,',
            sources: ',us,',
            types: ',origin,phase-data,',
            nst: 113,
            dmin: 3.387,
            rms: 0.82,
            gap: 80,
            magType: 'mb',
            type: 'earthquake',
            title: 'M 5.1 - ',
          },
          geometry: {
            type: 'Point',
            coordinates: [
              162.5373,
              55.5236,
              37.839,
            ],
          },
          id: 'us7000iren',
        },
        {
          type: 'Feature',
          properties: {
            mag: 5.4,
            place: '92 km SSE of Ust’-Kamchatsk Staryy, Russia',
            time: 1669067147081,
            updated: 1669154057896,
            tz: null,
            url: 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000iref',
            detail: 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000iref&format=geojson',
            felt: null,
            cdi: null,
            mmi: 3.815,
            alert: 'green',
            status: 'reviewed',
            tsunami: 0,
            sig: 449,
            net: 'us',
            code: '7000iref',
            ids: ',usauto7000iref,us7000iref,',
            sources: ',usauto,us,',
            types: ',internal-moment-tensor,losspager,moment-tensor,origin,phase-data,shakemap,',
            nst: 116,
            dmin: 3.471,
            rms: 1.2,
            gap: 88,
            magType: 'mww',
            type: 'earthquake',
            title: 'M 5.4 - 92 km SSE of Ust’-Kamchatsk Staryy, Russia',
          },
          geometry: {
            type: 'Point',
            coordinates: [
              162.9011,
              55.4323,
              10,
            ],
          },
          id: 'us7000iref',
        },
        {
          type: 'Feature',
          properties: {
            mag: 5.2,
            place: '241 km W of Bandon, Oregon',
            time: 1669045353572,
            updated: 1669229783637,
            tz: null,
            url: 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000irbr',
            detail: 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000irbr&format=geojson',
            felt: 40,
            cdi: 3.1,
            mmi: null,
            alert: null,
            status: 'reviewed',
            tsunami: 1,
            sig: 428,
            net: 'us',
            code: '7000irbr',
            ids: ',at00rlpfmz,us7000irbr,usauto7000irbr,',
            sources: ',at,us,usauto,',
            types: ',dyfi,impact-link,internal-moment-tensor,moment-tensor,oaf,origin,phase-data,',
            nst: 84,
            dmin: 1.733,
            rms: 0.35,
            gap: 159,
            magType: 'mww',
            type: 'earthquake',
            title: 'M 5.2 - 241 km W of Bandon, Oregon',
          },
          geometry: {
            type: 'Point',
            coordinates: [
              -127.3401,
              43.4836,
              10,
            ],
          },
          id: 'us7000irbr',
        },
        {
          type: 'Feature',
          properties: {
            mag: 5.5,
            place: '78 km SE of Nikolski, Alaska',
            time: 1669043369350,
            updated: 1669131009909,
            tz: null,
            url: 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000irbb',
            detail: 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000irbb&format=geojson',
            felt: null,
            cdi: null,
            mmi: 3.399,
            alert: 'green',
            status: 'reviewed',
            tsunami: 1,
            sig: 465,
            net: 'us',
            code: '7000irbb',
            ids: ',us7000irbb,at00rlpe3w,usauto7000irbb,ak022exqnaft,',
            sources: ',us,at,usauto,ak,',
            types: ',ground-failure,impact-link,internal-moment-tensor,losspager,moment-tensor,origin,phase-data,shakemap,',
            nst: 127,
            dmin: 0.735,
            rms: 0.64,
            gap: 61,
            magType: 'mww',
            type: 'earthquake',
            title: 'M 5.5 - 78 km SE of Nikolski, Alaska',
          },
          geometry: {
            type: 'Point',
            coordinates: [
              -168.2072,
              52.3536,
              13.929,
            ],
          },
          id: 'us7000irbb',
        },
        {
          type: 'Feature',
          properties: {
            mag: 5.6,
            place: 'Java, Indonesia',
            time: 1669011670003,
            updated: 1669250180256,
            tz: null,
            url: 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000ir9t',
            detail: 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000ir9t&format=geojson',
            felt: 137,
            cdi: 8.8,
            mmi: 8.596,
            alert: 'orange',
            status: 'reviewed',
            tsunami: 0,
            sig: 1121,
            net: 'us',
            code: '7000ir9t',
            ids: ',us7000ir9t,usauto7000ir9t,pt22325000,',
            sources: ',us,usauto,pt,',
            types: ',dyfi,general-text,ground-failure,internal-moment-tensor,internal-origin,losspager,losspager-admin,moment-tensor,origin,phase-data,shakemap,',
            nst: 84,
            dmin: 0.819,
            rms: 0.58,
            gap: 40,
            magType: 'mww',
            type: 'earthquake',
            title: 'M 5.6 - Java, Indonesia',
          },
          geometry: {
            type: 'Point',
            coordinates: [
              107.0946,
              -6.8531,
              10,
            ],
          },
          id: 'us7000ir9t',
        },
        {
          type: 'Feature',
          properties: {
            mag: 5.2,
            place: 'Izu Islands, Japan region',
            time: 1669004738072,
            updated: 1669005869040,
            tz: null,
            url: 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000ir9f',
            detail: 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000ir9f&format=geojson',
            felt: null,
            cdi: null,
            mmi: null,
            alert: null,
            status: 'reviewed',
            tsunami: 0,
            sig: 416,
            net: 'us',
            code: '7000ir9f',
            ids: ',usauto7000ir9f,us7000ir9f,',
            sources: ',usauto,us,',
            types: ',internal-moment-tensor,moment-tensor,origin,phase-data,',
            nst: 121,
            dmin: 3.909,
            rms: 0.65,
            gap: 90,
            magType: 'mww',
            type: 'earthquake',
            title: 'M 5.2 - Izu Islands, Japan region',
          },
          geometry: {
            type: 'Point',
            coordinates: [
              139.4019,
              29.2105,
              416.432,
            ],
          },
          id: 'us7000ir9f',
        },
      ],
      bbox: [
        -168.2072,
        -6.8531,
        10,
        162.9011,
        55.5236,
        416.432,
      ],
    },
  ],
};

const earthquakeSlice = createSlice({
  name: 'earthquakes',
  initialState,
  reducers: {
    joinMission(state, action) {
      state.earthquakes.unshift(action.payload);
    },
    leaveMission(state, action) {
      if (action.payload) {
        const temp = state.earthquakes.filter((earthquake) => earthquake.id !== action.payload);
        // eslint-disable-next-line
        state.earthquakes = temp;
      }
    },
  },
});

export const { joinMission, leaveMission } = earthquakeSlice.actions;
export default earthquakeSlice.reducer;
